= jaxrs-jwt: JAX-RS secured using JSON Web Tokens (JWTs)
:author: Martin Mazanek
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]

:level: Intermediate
:technologies: JAX-RS, Security
:source: {githubRepoUrl}

[abstract]
The `jaxrs-jwt` quickstart demonstrates a JAX-RS secured application using JSON Web Tokens (JWT) with Elytron.

:standalone-server-type: default
:archiveType: war
:includes-cli-scripts:

== What is it?

This quickstart demonstrates how to secure a JAX-RS service with JWTs using the Elytron subsystem.

There are 4 resource endpoints, plus another one for generating JWTs.

* `/rest/public` - Requires no authentication.
* `/rest/customer` - Can be accessed by users with `customer` role authority.
* `/rest/admin` - Can be accessed by users with `admin` role authority.
* `/rest/claims` - Can be accessed by any authenticated user and demonstrates how to extract token claims.
* `/rest/token` - `POST` endpoint for generating tokens from provided credentials.

NOTE: This quickstart asserts only few JWT claims for demonstration purposes. In your application, you should use all claims required by the specification you are using.

//*************************************************
// Add System Requirements
//*************************************************
// == System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

//*************************************************
// Add Use of JBoss Home Name
//*************************************************
// == Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

[[add_the_application_users]]
== Add the Application Users

This quickstart uses secured management interfaces and is built around the default `ApplicationRealm` as configured in the {productName} distribution. You must create the following application user to access the running application.

*@martinMazanek*: Does this quickstart need to add users with `customer` role? If so, see the `ejb-security-context-propagation` quickstart READNE for an exmample of how to do this. If not, you can delete this section.

[[generate_an_rs256_key_pair]]
== Generate an RS256 Key Pair

Elytron uses RS256 (SHA256withRSA), RS384 (SHA384withRSA), and RS512 (SHA512withRSA) asymmetric keys for signing JWTs. The keys must be in PKCS#8 format.

You can generate your own RS256 key pair by running `generateKeys.sh` script include in the root directory of this quickstart.

Open a new terminal, navigate to the root directory of this quickstart, and run the following command:

[source,subs="+quotes,attributes+",options="nowrap"]
----
$ ./generateKeys.sh
----

NOTE: The private key implementation in `JwtRestClient.java` file is for demonstration purposes only. Never leave your private keys in plaintext. Use a keystore or other protected store instead!

//*************************************************
// Back up the server configuration files
//*************************************************
// == Back Up the {productName} Standalone Server Configuration
include::../shared-doc/back-up-server-standalone-configuration.adoc[leveloffset=+1]

//*************************************************
// Start the server with the default profile
//*************************************************
// == Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]

[[configure_the_server]]
== Configure the Server

You configure the security domain by running JBoss CLI commands. For your convenience, this quickstart batches the commands into a `configure-elytron.cli` script provided in the root directory of this quickstart.

. Before you begin, make sure you do the following:

* xref:back_up_standalone_server_configuration[Back up the {productName} standalone server configuration] as described above.
* xref:start_the_eap_standalone_server[Start the {productName} server with the standalone default profile] as described above.

. Review the `configure-elytron.cli` file in the root of this quickstart directory. This script adds the configuration that enables Elytron security for the quickstart deployment. Comments in the script describe the purpose of each block of commands.
+
IMPORTANT: This script contains placeholder PEM public key to make the deployment of this quickstart easy. DO _not_ use this key for anything but testing purposes! You must generate your own key pair for your own application.

. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing `__{jbossHomeName}__` with the path to your server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=configure-elytron.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.
+

. Because this example quickstart demonstrates security, system exceptions are thrown when secured EJB access is attempted by an invalid user. If you want to review the security exceptions in the server log, you can skip this step. If you want to suppress these exceptions in the server log, run the following command, replacing `__{jbossHomeName}__` with the path to your server:
[[suppress_system_exceptions]]
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=configure-system-exception.cli
----
+
NOTE: For Windows,use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.
+

You should see the following result when you run the script:
+
[source,options="nowrap"]
----
The batch executed successfully
----

. Stop the {productName} server.

== Review the Modified Server Configuration

After stopping the server, open the `__{jbossHomeName}__/standalone/configuration/standalone.xml` file and review the changes.

. The following `token-realm` was added to the `security-realms` element in the `elytron` subsystem.
+
[source,xml,options="nowrap"]
----
<token-realm name="jwt-realm" principal-claim="sub">
    <jwt issuer="quickstart-jwt-issuer" audience="jwt-audience" public-key="-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy45LzIcnzQzEMbJ/vbFU080aqq/kLzSsCJKwIsY2FF5mAyH8gKHf9OOAImsalV5elrOGy27fUNIJlBmAjhyW4wJAhs/PfrubhmtZhBJV4f4CGEJb7hteWD8h+TPr2zDz0w95PibCk1pbqniy9ARBLN/NkZE5fSHmC8IyMXDwJI54B7C/rtZKtW2nhL45q7xUvM04mhhrKhA9ce1DD+W0sk4Ogp2mPX3yr71+1siYPUebQgXmTMPU2Z6C27he4bTAb8XhDUbBvFQih4xTas4YJqbpR+eaT+PrPC7+mIFcyHPLntTjKHVqxTeUR4x6VxRwBXOxhh5CKTPZeVr8mBI53wIDAQAB-----END PUBLIC KEY-----"/>
</token-realm>
----
. The following `security-domain` was added, which uses the `jwt-realm`.
+
[source,xml,options="nowrap"]
----
<security-domain name="jwt-domain" default-realm="jwt-realm" permission-mapper="default-permission-mapper">
    <realm name="jwt-realm" role-decoder="groups-to-roles"/>
</security-domain>
----

. The following HTTP authentication factory was added, which uses `BEARER_TOKEN` and the `jwt-realm`.
+
[source,xml,options="nowrap"]
----
<http-authentication-factory name="jwt-http-authentication" http-server-mechanism-factory="global" security-domain="jwt-domain">
    <mechanism-configuration>
        <mechanism mechanism-name="BEARER_TOKEN">
            <mechanism-realm realm-name="jwt-realm"/>
        </mechanism>
    </mechanism-configuration>
</http-authentication-factory>
----

. Finally, the application security domain is configured in Undertow to use the new HTTP authentication factory.
+
[source,xml,options="nowrap"]
----

<application-security-domains>
    <application-security-domain name="other" http-authentication-factory="jwt-http-authentication"/>
</application-security-domains>
----

//*************************************************
// Build and deploy the quickstart WAR
//*************************************************
// == Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]

[[access_the_application]]
== Access the Application

Before you run the client, make sure you have already successfully deployed the REST to the server in the previous step and that your terminal is still in the same folder.

Type the following command to execute the client.

[source,options="nowrap"]
----
$ mvn exec:java
----

== Investigate the Console Output

When you run the `mvn exec:java` command, you see the following output.

[source,options="nowrap"]
----
output goes here
----

*@martinMazanek*: You might want to let them know what to expect and paste the output above.

//*************************************************
// Undeploy the quickstart archive
//*************************************************
// == Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+1]

//************************************************************
// Restore the {productName} Standalone Server Configuration
//************************************************************
// == Restore the {productName} Standalone Server Configuration
:restoreScriptName: restore-configuration.cli
include::../shared-doc/restore-standalone-server-configuration.adoc[leveloffset=+1]

*@martinMazanek*: You probably need to create a scripts named `restore-configuration.cli` that reverts the changes. If it is too messy, just delete this section

// Additional information about this script
This script reverts the changes made to the `undertow`  and `elytron` subsystem.You should see the following result when you run the script.

[source,options="nowrap"]
----
The batch executed successfully
process-state: reload-required
----

//******************************************************
// Restore the standalone server configuration manually
//******************************************************
// == Restore the {productName} Standalone Server Configuration Manually
include::../shared-doc/restore-standalone-server-configuration-manual.adoc[leveloffset=+2]


//*************************************************
// Add JBoss Developer Studio instructions
//*************************************************
// == Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]

// Additional JBoss Developer Studio instructions
* Make sure you configure the server by running the JBoss CLI commands as described above under xref:configure_the_server[Configure the Server]. Stop the server at the end of that step.
* Make sure you xref:restore-the-server-configuration[restore the server configuration] when you have completed testing this quickstart.

*@martinMazanek*: Can the quickstart be run in JBoss Developer Studio? If so, make sure any special instructions are added. If not, you can remove this section.

//*************************************************
// Add info to debug the application
//*************************************************
// == Debug the Application
include::../shared-doc/debug-the-application.adoc[leveloffset=+1]
